// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/restaurant-orders": {
            "put": {
                "description": "Updates the status of an existing restaurant order.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurant_orders"
                ],
                "summary": "Update a restaurant order status",
                "parameters": [
                    {
                        "description": "Restaurant Order Update Data",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateRestaurantOrderDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order updated successfully"
                    }
                }
            },
            "post": {
                "description": "Creates a new restaurant order with the provided menu IDs and total.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurant_orders"
                ],
                "summary": "Create a new restaurant order",
                "parameters": [
                    {
                        "description": "Restaurant Order Data",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateRestaurantOrderDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.RestaurantOrder"
                        }
                    }
                }
            }
        },
        "/restaurant-orders/{id}": {
            "get": {
                "description": "Retrieves a restaurant order by its unique ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurant_orders"
                ],
                "summary": "Get restaurant order by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Restaurant Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.RestaurantOrder"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreateRestaurantOrderDTO": {
            "type": "object",
            "properties": {
                "menu_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "dtos.RestaurantOrder": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "menu_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "dtos.UpdateRestaurantOrderDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CJ Restaurant Order-Service API",
	Description:      "API for managing restaurant orders.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
